# Generated by Django 5.1.5 on 2025-04-12 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jalali_created_at', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('users', models.ManyToManyField(related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('temperature', models.FloatField()),
                ('times', models.DateTimeField(auto_now_add=True)),
                ('jalali_times', models.CharField(blank=True, max_length=20)),
                ('device_id_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Track.device')),
            ],
        ),
    ]
